### ISSUE TITLE
Fatal error: 'CouchbaseLiteListener/CBLListener.h' file not found (IOS)

### ISSUE THREAD

**Issue by sabinayakc** [couchbaselabs/react-native-couchbase-lite#132]
Hello,

I am having a problem with installing couchbase lite with IOS. I followed all the steps mentioned in the github page but still seem to have no luck.

Here is the screenshot
<img width="1339" alt="screen shot 2017-11-01 at 11 56 15 am" src="https://user-images.githubusercontent.com/13154166/32286704-59b29262-befc-11e7-968f-b616f663bbaa.png">

**Comment by denissb** [comment]
I am facing the same problem, can anyone assist?
It seems the instructions in the install manual are outdated.

**Comment by denissb** [comment]
After some investigation I found that the problem lies in the Header search paths that Xcode uses to resolve the import statements.

In oder to fix this problem you need to make sure that the path to Couchbase frameworks can be resolved via **Framework Search Paths** in the projects build settings in Xcode. 

Typically in Xcode framework paths are resolved from the $(PROJECT_DIR) which in case of RN is usually in /ios folder. So to fix the problem you simply need to copy the framework files to that location.

For example:
![screenshot at nov 03 22-35-27](https://user-images.githubusercontent.com/2261330/32397205-f5d69984-c0e8-11e7-862f-037169d55044.png)

I made a [PR #133](https://github.com/couchbaselabs/react-native-couchbase-lite/pull/133) and added it to the installation manual + applied a fix for version RN >=0.40;

**Comment by sabinayakc** [comment]
Thanks @denissb . I got pass through the build but now I am getting the following error. Could you tell me how you are initializing couchbase in your project? 
I have it in my App.js file inside the "componentDidMount()" lifecycle hook. 
<img width="421" alt="screen shot 2017-11-05 at 6 46 44 pm" src="https://user-images.githubusercontent.com/13154166/32421101-648b196e-c25a-11e7-9b4a-2ff954164ee8.png">

**Comment by denissb** [comment]
@Sabdeth - It seems you have an issue linking of the library. (Native module not exposed to JS thread) Please follow the manual steps described [here](https://github.com/couchbaselabs/react-native-couchbase-lite/wiki/Other-Installation-Options) and make sure you have the linked libraries configured properly on Xcode(libsqlite3.0.tbd, libz.tbd, etc. - I had issues with that)

**Comment by sabinayakc** [comment]
Thanks @denissb . I did follow those steps. Both the manual and pod file. But I have build issues still.
Here is my package.json file. Could you tell me how your package.json looks like?

`	"dependencies": {
		"react": "16.0.0",
		"react-native": "0.50.1",
		"react-native-couchbase-lite": "^0.6.0"
	},
	"devDependencies": {
		"babel-jest": "21.2.0",
		"babel-preset-react-native": "4.0.0",
		"jest": "21.2.1",
		"react-test-renderer": "16.0.0"
	},
	"jest": {
		"preset": "react-native"
	}`

**Comment by jamesnocentini** [comment]
@denissb could you confirm that the steps you followed fixed the issue in your Xcode project?

**Comment by sabinayakc** [comment]
After getting #133 changes and following @denissb's suggestions I was able to load CouchbaseLite in IOS. Thanks!
