### ISSUE TITLE
New ReactCBLite.init API breaks my project

### ISSUE THREAD

**Issue by adamski** [couchbaselabs/react-native-couchbase-lite#71]
The new API introduced in commit eec870b breaks my project. I don't understand the random username and password generation. 

Please try and avoid breaking changes unless deemed necessary and if so please consult affected users. Thanks!

**Comment by npomfret** [comment]
Hi

This change isn't released yet, which is why the docs haven't been updated.  For now I'd suggest going for the official npm version.

However, if you do want to work off master you no longer need to supply those parameters.  Both the iOS version and the android version will generate credentials and pass them back to you:

```
    ReactCBLite.init((cblUrl, err) => {
        if(err) {
           // deal with error
        } else {
          console.log("cbl started at:", cblUrl);
        }
    });

```

**Comment by adamski** [comment]
Ah I see. I was working with a branch that I checked out from master. I will track the latest release instead. Thanks.

**Comment by adamski** [comment]
I still don't understand how to use this changed API - it cannot log into my db, I get a 401, as the username password are `admin:password`. I would like to use master if possible.
