### ISSUE TITLE
Unable to create design documents

### ISSUE THREAD

**Issue by MohsinTariq10** [couchbaselabs/react-native-couchbase-lite#91]
I am using your example, the local db is created succesfully and it also replicates the remote db to local db too but when i try to create design document to create views i get this error. 
`{status: 409, error: "conflict", reason: "conflict"}`
Secondly how can i specify the revision number for the views ?

**Comment by npomfret** [comment]
From the [docs](http://developer.couchbase.com/documentation/mobile/current/develop/references/couchbase-lite/rest-api/index.html#operation---db--_all_docs-get) it looks like you simple specify the revision in the document body.

**Comment by MohsinTariq10** [comment]
`database.createDesignDocument('_design/mem', {
            views: {
              members: {
                map: 'function (doc) { if(doc.SeatType) emit(doc._id, doc);}'
              }
            },
            _rev : '3'
          })
          .then((res) => {
            console.log("created design doc", res);
          });`
I am creating/updating the design document like above, as you have mentioned from the docs i have included the _rev inside the design document but still getting the same conflict error.

**Comment by npomfret** [comment]
This is probably something to ask on the couchbase forum, nothing really to do with this project.

However, I seem to remember than when I did this in the past the view in the design document would have the old data in after I updated the design doc.  CBL didn't seem to reindex the view when the design doc changed.  For this reason I don't update them any more, i just change the name of the design doc in order to create a bunch of views from scratch.

**Comment by MohsinTariq10** [comment]
What I was doing wrong in terms of creating the design docs is that I was prefixing the name with '_design/' removing it solved the problem of creating design documents, although i would agree that the reindexing is not working,  and i am using the same hack of changing the name.

**Comment by npomfret** [comment]
Maybe still ask on the forum, there might be a better way to do it. https://forums.couchbase.com
